# @generated by scripts/reqgen.py from metaobjects/meta.axi-toolkit.yaml -- DO NOT EDIT.
#
# Regenerate with `python3.11 scripts/reqgen.py generate`; CI fails if this file and
# the declaration disagree. Editing it by hand is how a check stops matching the claim
# it was written for.
"""The declared requirements, as checks.

Each test below is one fact from ``metaobjects/meta.axi-toolkit.yaml``, judged by the
relation its projection kind implies, against the value in ``capture.json`` -- which is
machine-written from the authorities and never edited. The docstring is the requirement
that asked for the check, and what breaking it looks like.

The last test is the one that makes the rest mean anything: it breaks every check in
turn and requires each to fail. A check that has never failed is not yet a check.
"""

from __future__ import annotations

import json
import pathlib

import pytest

from conformance import projections, relations

CAPTURE = json.loads(
    (pathlib.Path(__file__).parent / "capture.json").read_text(encoding="utf-8")
)["facts"]

#: fact -> (relation, requirement paths). Read by the checks and by the vacuity test.
CHECKS = {
    "envConfigErrorCodes": (
        "equal",
        (
            "credentialsComeFromTheEnvironmentOnly.bothToolsMessagesAreReproduced",
        ),
    ),
    "errorExitCodes": (
        "equal",
        (
            "anErrorCarriesItsOwnFix.theErrorVocabularyIsShared",
        ),
    ),
    "errorFaultClasses": (
        "equal",
        (
            "anErrorCarriesItsOwnFix.theErrorVocabularyIsShared",
        ),
    ),
    "errorTypeNames": (
        "equal",
        (
            "anErrorCarriesItsOwnFix.theErrorVocabularyIsShared",
            "thePureModulesImportNoHttpLibrary",
        ),
    ),
    "haServiceModelDefinitions": (
        "equal",
        (
            "theDomainTierFollows.theHomeAssistantServiceModelIsHere",
            "anExtractedModuleIsGatedAgainstItsOriginUntilTheToolTakesIt",
        ),
    ),
    "toonCaseOptionNames": (
        "equal",
        (
            "toonIsTheWireFormat.noFixtureSettingIsIgnored",
        ),
    ),
    "toonEncodeCaseCount": (
        "equal",
        (
            "toonIsTheWireFormat.theWholePublishedSuiteRuns",
        ),
    ),
    "toonExercisedDelimiters": (
        "equal",
        (
            "toonIsTheWireFormat.noFixtureSettingIsIgnored",
        ),
    ),
    "toonFixtureCategories": (
        "equal",
        (
            "toonIsTheWireFormat.theWholePublishedSuiteRuns",
        ),
    ),
    "toonFixtureDigests": (
        "equal",
        (
            "toonIsTheWireFormat.theFixturesAreStillTheSpecificationsOpinion",
            "noCheckCarriesAHandTypedExpectedValue",
        ),
    ),
    "credentialSpecCells": (
        "covers",
        (
            "credentialsComeFromTheEnvironmentOnly.everyCredentialSpecInUseIsExpressible",
        ),
    ),
    "recoveryShapeCells": (
        "covers",
        (
            "anErrorCarriesItsOwnFix.everyRecoveryShapeInUseIsExpressible",
            "noCheckIsVacuous",
        ),
    ),
    "redactionShapeCells": (
        "covers",
        (
            "aCredentialCannotReachStdout.everyCredentialShapeInUseIsExpressible",
        ),
    ),
    "haCredentialMessages": (
        "wire",
        (
            "credentialsComeFromTheEnvironmentOnly.bothToolsMessagesAreReproduced",
        ),
    ),
    "haNormalizedUrls": (
        "wire",
        (
            "credentialsComeFromTheEnvironmentOnly.bothToolsUrlNormalisationIsReproduced",
        ),
    ),
    "haRecoveryLines": (
        "wire",
        (
            "anErrorCarriesItsOwnFix.recoveryRendersByteForByte",
            "recoveryIsCarriedAsData",
        ),
    ),
    "plexCredentialMessages": (
        "wire",
        (
            "credentialsComeFromTheEnvironmentOnly.bothToolsMessagesAreReproduced",
        ),
    ),
    "plexNormalizedUrls": (
        "wire",
        (
            "credentialsComeFromTheEnvironmentOnly.bothToolsUrlNormalisationIsReproduced",
        ),
    ),
    "plexRecoveryLines": (
        "wire",
        (
            "anErrorCarriesItsOwnFix.recoveryRendersByteForByte",
            "recoveryIsCarriedAsData",
        ),
    ),
    "redactionSamples": (
        "wire",
        (
            "aCredentialCannotReachStdout.everyToolSampleIsStillRedacted",
            "noCheckIsVacuous",
        ),
    ),
    "toonEncodeCases": (
        "wire",
        (
            "toonIsTheWireFormat.everyPublishedCaseIsReproduced",
            "noCheckCarriesAHandTypedExpectedValue",
        ),
    ),
    "credentialContract": (
        "differential",
        (
            "theTwoToolsCopiesAgreeOrTheDisagreementIsReported",
        ),
    ),
    "encoderDigest": (
        "differential",
        (
            "theTwoToolsCopiesAgreeOrTheDisagreementIsReported",
        ),
    ),
    "errorContract": (
        "differential",
        (
            "theTwoToolsCopiesAgreeOrTheDisagreementIsReported",
        ),
    ),
    "redactionContract": (
        "differential",
        (
            "theTwoToolsCopiesAgreeOrTheDisagreementIsReported",
        ),
    ),
}

#: fact -> the subject, in the form its relation consumes: a value for `equal`, the
#: covered subset for `covers`, and the callable itself for `wire` and `differential`.
SUBJECTS = {
    "envConfigErrorCodes": lambda captured: projections.subject_env_config_error_codes(),
    "errorExitCodes": lambda captured: projections.subject_error_exit_codes(),
    "errorFaultClasses": lambda captured: projections.subject_error_fault_classes(),
    "errorTypeNames": lambda captured: projections.subject_error_type_names(),
    "haServiceModelDefinitions": lambda captured: projections.subject_ha_service_model_definitions(),
    "toonCaseOptionNames": lambda captured: projections.subject_toon_case_option_names(),
    "toonEncodeCaseCount": lambda captured: projections.subject_toon_encode_case_count(),
    "toonExercisedDelimiters": lambda captured: projections.subject_toon_exercised_delimiters(),
    "toonFixtureCategories": lambda captured: projections.subject_toon_fixture_categories(),
    "toonFixtureDigests": lambda captured: projections.subject_toon_fixture_digests(),
    "credentialSpecCells": lambda captured: projections.subject_credential_spec_cells(captured),
    "recoveryShapeCells": lambda captured: projections.subject_recovery_shape_cells(captured),
    "redactionShapeCells": lambda captured: projections.subject_redaction_shape_cells(captured),
    "haCredentialMessages": lambda captured: projections.subject_ha_credential_messages,
    "haNormalizedUrls": lambda captured: projections.subject_ha_normalized_urls,
    "haRecoveryLines": lambda captured: projections.subject_ha_recovery_lines,
    "plexCredentialMessages": lambda captured: projections.subject_plex_credential_messages,
    "plexNormalizedUrls": lambda captured: projections.subject_plex_normalized_urls,
    "plexRecoveryLines": lambda captured: projections.subject_plex_recovery_lines,
    "redactionSamples": lambda captured: projections.subject_redaction_samples,
    "toonEncodeCases": lambda captured: projections.subject_toon_encode_cases,
    "credentialContract": lambda captured: projections.subject_credential_contract,
    "encoderDigest": lambda captured: projections.subject_encoder_digest,
    "errorContract": lambda captured: projections.subject_error_contract,
    "redactionContract": lambda captured: projections.subject_redaction_contract,
}


def _judge(fact, subject=None, captured=None):
    relation = CHECKS[fact][0]
    if captured is None:
        captured = CAPTURE[fact]
    if subject is None:
        subject = SUBJECTS[fact](captured)
    problem = relations.RELATIONS[relation](subject, captured)
    if problem is not None:
        pytest.fail(f"{fact} ({relation}): {problem}", pytrace=False)


def test_env_config_error_codes():
    """The message and the recovery of every configuration failure either tool raises are reproduced exactly under that tool's declared spec.

    Requirement: credentialsComeFromTheEnvironmentOnly.bothToolsMessagesAreReproduced (functional, live).
    Breaking it looks like: A configuration error whose wording changed on extraction, breaking a tool's own assertion on it.
    """
    _judge("envConfigErrorCodes")


def test_error_exit_codes():
    """The exit codes, fault classes and error types this package declares are the ones the two tools already declare.

    Requirement: anErrorCarriesItsOwnFix.theErrorVocabularyIsShared (functional, live).
    Breaking it looks like: A tool taking this package and finding an exit code or an error type it used has gone missing.
    """
    _judge("errorExitCodes")


def test_error_fault_classes():
    """The exit codes, fault classes and error types this package declares are the ones the two tools already declare.

    Requirement: anErrorCarriesItsOwnFix.theErrorVocabularyIsShared (functional, live).
    Breaking it looks like: A tool taking this package and finding an exit code or an error type it used has gone missing.
    """
    _judge("errorFaultClasses")


def test_error_type_names():
    """The exit codes, fault classes and error types this package declares are the ones the two tools already declare.

    Requirement: anErrorCarriesItsOwnFix.theErrorVocabularyIsShared, thePureModulesImportNoHttpLibrary (functional, live).
    Breaking it looks like: A tool taking this package and finding an exit code or an error type it used has gone missing.
    """
    _judge("errorTypeNames")


def test_ha_service_model_definitions():
    """The reader for the service model an installation publishes is in this package, definition for definition as the tool it came from has it.

    Requirement: theDomainTierFollows.theHomeAssistantServiceModelIsHere, anExtractedModuleIsGatedAgainstItsOriginUntilTheToolTakesIt (functional, live).
    Breaking it looks like: A move that quietly improved something on the way, so the tool taking it back gets a behaviour change it did not ask for and cannot see.
    """
    _judge("haServiceModelDefinitions")


def test_toon_case_option_names():
    """Every option and delimiter the published cases exercise is one the runner applies.

    Requirement: toonIsTheWireFormat.noFixtureSettingIsIgnored (functional, live).
    Breaking it looks like: A case carrying an option the runner does not recognise, run with default settings and reported as a pass.
    """
    _judge("toonCaseOptionNames")


def test_toon_encode_case_count():
    """The conformance run covers every case the vendored specification publishes, and says how many that is by counting them.

    Requirement: toonIsTheWireFormat.theWholePublishedSuiteRuns (functional, live).
    Breaking it looks like: A fixture file that stops being collected, shrinking the score in silence while the suite stays green.
    """
    _judge("toonEncodeCaseCount")


def test_toon_exercised_delimiters():
    """Every option and delimiter the published cases exercise is one the runner applies.

    Requirement: toonIsTheWireFormat.noFixtureSettingIsIgnored (functional, live).
    Breaking it looks like: A case carrying an option the runner does not recognise, run with default settings and reported as a pass.
    """
    _judge("toonExercisedDelimiters")


def test_toon_fixture_categories():
    """The conformance run covers every case the vendored specification publishes, and says how many that is by counting them.

    Requirement: toonIsTheWireFormat.theWholePublishedSuiteRuns (functional, live).
    Breaking it looks like: A fixture file that stops being collected, shrinking the score in silence while the suite stays green.
    """
    _judge("toonFixtureCategories")


def test_toon_fixture_digests():
    """Each vendored fixture still hashes to the digest recorded when it was vendored.

    Requirement: toonIsTheWireFormat.theFixturesAreStillTheSpecificationsOpinion, noCheckCarriesAHandTypedExpectedValue (functional, live).
    Breaking it looks like: A fixture edited to make a failing encoder pass, which is no longer the specification's opinion about anything.
    """
    _judge("toonFixtureDigests")


def test_credential_spec_cells():
    """Every way the two tools differ in how they read credentials is a difference the credential spec can carry.

    Requirement: credentialsComeFromTheEnvironmentOnly.everyCredentialSpecInUseIsExpressible (functional, live).
    Breaking it looks like: A tool difference with nowhere to go, so that tool keeps its own copy of the loader.
    """
    _judge("credentialSpecCells")


def test_recovery_shape_cells():
    """Every shape of recovery line the two tools actually emit is one the recovery vocabulary can express.

    Requirement: anErrorCarriesItsOwnFix.everyRecoveryShapeInUseIsExpressible, noCheckIsVacuous (functional, live).
    Breaking it looks like: A shape present in the tools' output that has no intent to carry it, so extraction quietly drops it to free text.
    """
    _judge("recoveryShapeCells")


def test_redaction_shape_cells():
    """Every shape of credential pattern the two tools carry is one this package's pattern registration can express.

    Requirement: aCredentialCannotReachStdout.everyCredentialShapeInUseIsExpressible (functional, live).
    Breaking it looks like: A tool-specific pattern that cannot be registered, so the tool keeps a private copy of the redactor and the drift begins again.
    """
    _judge("redactionShapeCells")


def test_ha_credential_messages():
    """The message and the recovery of every configuration failure either tool raises are reproduced exactly under that tool's declared spec.

    Requirement: credentialsComeFromTheEnvironmentOnly.bothToolsMessagesAreReproduced (functional, live).
    Breaking it looks like: A configuration error whose wording changed on extraction, breaking a tool's own assertion on it.
    """
    _judge("haCredentialMessages")


def test_ha_normalized_urls():
    """A base URL normalises to what the owning tool normalises it to, including its scheme default and its port default.

    Requirement: credentialsComeFromTheEnvironmentOnly.bothToolsUrlNormalisationIsReproduced (functional, live).
    Breaking it looks like: A bare host that silently became http:// for the tool whose default is TLS, sending its token in the clear.
    """
    _judge("haNormalizedUrls")


def test_ha_recovery_lines():
    """Rendering a recovery intent for a shell reproduces, byte for byte, the line the tool that owns it prints today.

    Requirement: anErrorCarriesItsOwnFix.recoveryRendersByteForByte, recoveryIsCarriedAsData (functional, live).
    Breaking it looks like: A recovery line that reads slightly differently after extraction, so the tool's own suite fails on a diff nobody intended.
    """
    _judge("haRecoveryLines")


def test_plex_credential_messages():
    """The message and the recovery of every configuration failure either tool raises are reproduced exactly under that tool's declared spec.

    Requirement: credentialsComeFromTheEnvironmentOnly.bothToolsMessagesAreReproduced (functional, live).
    Breaking it looks like: A configuration error whose wording changed on extraction, breaking a tool's own assertion on it.
    """
    _judge("plexCredentialMessages")


def test_plex_normalized_urls():
    """A base URL normalises to what the owning tool normalises it to, including its scheme default and its port default.

    Requirement: credentialsComeFromTheEnvironmentOnly.bothToolsUrlNormalisationIsReproduced (functional, live).
    Breaking it looks like: A bare host that silently became http:// for the tool whose default is TLS, sending its token in the clear.
    """
    _judge("plexNormalizedUrls")


def test_plex_recovery_lines():
    """Rendering a recovery intent for a shell reproduces, byte for byte, the line the tool that owns it prints today.

    Requirement: anErrorCarriesItsOwnFix.recoveryRendersByteForByte, recoveryIsCarriedAsData (functional, live).
    Breaking it looks like: A recovery line that reads slightly differently after extraction, so the tool's own suite fails on a diff nobody intended.
    """
    _judge("plexRecoveryLines")


def test_redaction_samples():
    """Every sample either tool's own redactor cleans, this one cleans to the same bytes.

    Requirement: aCredentialCannotReachStdout.everyToolSampleIsStillRedacted, noCheckIsVacuous (functional, live).
    Breaking it looks like: A credential shape one tool catches today and this package lets through after the tools adopt it.
    """
    _judge("redactionSamples")


def test_toon_encode_cases():
    """Every encode case the vendored TOON specification publishes encodes to the bytes the specification records for it.

    Requirement: toonIsTheWireFormat.everyPublishedCaseIsReproduced, noCheckCarriesAHandTypedExpectedValue (functional, live).
    Breaking it looks like: A published case whose emitted bytes differ from the fixture's, on a build that still reports a passing conformance score.
    """
    _judge("toonEncodeCases")


def test_credential_contract():
    """For every contract this package takes over, the two tools' copies are compared against each other, and this package matches the copy they agree on.

    Requirement: theTwoToolsCopiesAgreeOrTheDisagreementIsReported (architectural, live).
    Breaking it looks like: A fix landing in one tool's copy and not the other's, invisible until someone runs both against the same fixtures.
    """
    _judge("credentialContract")


def test_encoder_digest():
    """For every contract this package takes over, the two tools' copies are compared against each other, and this package matches the copy they agree on.

    Requirement: theTwoToolsCopiesAgreeOrTheDisagreementIsReported (architectural, live).
    Breaking it looks like: A fix landing in one tool's copy and not the other's, invisible until someone runs both against the same fixtures.
    """
    _judge("encoderDigest")


def test_error_contract():
    """For every contract this package takes over, the two tools' copies are compared against each other, and this package matches the copy they agree on.

    Requirement: theTwoToolsCopiesAgreeOrTheDisagreementIsReported (architectural, live).
    Breaking it looks like: A fix landing in one tool's copy and not the other's, invisible until someone runs both against the same fixtures.
    """
    _judge("errorContract")


def test_redaction_contract():
    """For every contract this package takes over, the two tools' copies are compared against each other, and this package matches the copy they agree on.

    Requirement: theTwoToolsCopiesAgreeOrTheDisagreementIsReported (architectural, live).
    Breaking it looks like: A fix landing in one tool's copy and not the other's, invisible until someone runs both against the same fixtures.
    """
    _judge("redactionContract")


@pytest.mark.parametrize("fact", sorted(CHECKS))
def test_no_check_is_vacuous(fact):
    """Every check above fails when the thing it names is broken.

    The mutations come from the relation, not from this file: each relation knows what
    a violation of itself looks like, so a new fact gets a vacuity proof without anyone
    writing one. A relation that produced no mutation would let a check through
    unproven, so that is a failure too.
    """
    relation = CHECKS[fact][0]
    captured = CAPTURE[fact]
    subject = SUBJECTS[fact](captured)
    broken = list(relations.mutations(relation, subject, captured))
    assert broken, f"{fact} ({relation}): the relation offers no way to break it"
    for description, mutated_subject, mutated_capture in broken:
        problem = relations.RELATIONS[relation](mutated_subject, mutated_capture)
        assert problem is not None, (
            f"{fact} ({relation}): the check still passed when {description}. "
            "It is not testing what it claims to."
        )
