"""The three generators. Each is a ``name`` and a ``generate(ctx)`` returning files.

What a model does not say is emitted exactly as it was before a model could say it: a
template below is kept whole and a choice adds to it or swaps one piece of it, so that a
consumer who chooses nothing regenerates the files it has, to the byte.

Everything emitted is laid out the way ``ruff format`` leaves it -- one item to a line
behind a trailing comma -- so the committed output passes the project's own formatter
whatever line length it is set to, and a regeneration is a diff of the lines that moved.
"""

from __future__ import annotations

import json

from metaobjects.codegen.generator import EmittedFile

from . import model


def _header(generator: str) -> str:
    return (
        f"# @generated by metaobjects (metagen:{generator}) from the model in metaobjects/.\n"
        "# Do not edit: change the metadata and regenerate. A hand edit fails\n"
        "# `metaobjects verify --codegen`.\n"
    )


def _string(value: str) -> str:
    if '"' in value and "'" not in value:
        return repr(value)
    return json.dumps(value, ensure_ascii=False)


def _literal(value, depth: int = 0) -> str:
    """A tuple, a dict or a string, as the formatter would leave it."""
    pad, end = "    " * (depth + 1), "    " * depth
    if isinstance(value, dict):
        if not value:
            return "{}"
        items = (f"{pad}{_string(k)}: {_literal(v, depth + 1)},\n" for k, v in value.items())
        return "{\n" + "".join(items) + end + "}"
    if isinstance(value, tuple):
        if not value:
            return "()"
        if len(value) == 1:
            return f"({_literal(value[0], depth)},)"
        return "(\n" + "".join(f"{pad}{_literal(v, depth + 1)},\n" for v in value) + end + ")"
    return _string(value)


def _assign(name: str, value) -> str:
    return f"{name} = {_literal(value)}\n"


def _qualified(owner: str, name: str) -> str:
    """A name of another object, spelled as the model spells a reference to one."""
    return f"{owner}.{name}"


def _column_reads(row, column: str) -> tuple:
    """What one column reads: its own object's names bare, any other object's qualified."""
    others = row.also.get(column, {})
    return row.reads[column] + tuple(
        _qualified(owner, name) for owner, names in others.items() for name in names
    )


class Rows:
    name = "metagen-rows"

    def generate(self, ctx):
        rows = model.read(ctx.loaded_root).rows
        reads = {
            row.key: {column: _column_reads(row, column) for column in row.reads} for row in rows
        }
        key_of = {
            row.key: {column: _qualified(*under) for column, under in row.key_of.items()}
            for row in rows
            if row.key_of
        }
        more = ""
        if any(row.also for row in rows):
            more += (
                "\n"
                "A name in ``READS`` written ``package::Object.name`` is read from that other\n"
                "object, and not from the one the row is made of.\n"
            )
        if key_of:
            more += (
                "\n"
                "``KEY_OF`` is each column that is the key its object sits under in a map, and\n"
                "the map: that key is in no answer as a name, so ``READS`` cannot carry it.\n"
            )
        content = (
            _header("rows")
            + '"""The rows this tool prints: the columns each offers, and what each one reads.\n'
            "\n"
            "``FIELDS`` is every column a row can carry, in the order they are documented and\n"
            "printed. ``DEFAULT`` is the set shown when no columns are asked for. ``READS`` is\n"
            "the attributes of the upstream object that each column is read from: nothing at\n"
            "run time reads it, and it is here so that what a column is made of ships with\n"
            "the column, for the test suite and for whatever builds on this package.\n"
            + more
            + '"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            + _assign("FIELDS", {row.key: tuple(row.reads) for row in rows})
            + "\n"
            + _assign("DEFAULT", {row.key: row.default for row in rows})
            + "\n"
            + _assign("READS", reads)
            + ("\n" + _assign("KEY_OF", key_of) if key_of else "")
        )
        return [EmittedFile(path="rows.py", content=content)]


#: The helper every builder of one wire format goes through. It is one template so that
#: the two refusals cannot come to differ in anything but their words.
_BUILDER = """

def @helper@(kind: str, @members@: dict) -> dict:
    unknown = sorted(set(@members@) - set(ATTRIBUTES[kind]))
    if unknown:
        raise KeyError(
            f"{kind}: {unknown} is not @a member@ the model declares, and a double may "
            "not invent one; declare it, and the capture check will say whether a real "
            "server sends it"
        )
    absent = [name for name in REQUIRED[kind] if @members@.get(name) in (None, "")]
    if absent:
        raise KeyError(f"{kind}: a real {ELEMENT[kind]} @whole@ always carries {absent}")
    return @members@
"""

#: By wire format: what its helper is called, what a builder calls its argument, and what
#: one answer and a member of it are called. The emitted tables keep one name each
#: whatever the format, so nothing that imports them has to know which it is.
_WORDS = {
    "xml-attributes": {
        "helper": "_element",
        "members": "attributes",
        "a member": "an attribute",
        "whole": "element",
    },
    "json": {
        "helper": "_object",
        "members": "keys",
        "a member": "a key",
        "whole": "object",
    },
}


def _builder(form: str) -> str:
    text = _BUILDER
    for token, word in _WORDS[form].items():
        text = text.replace(f"@{token}@", word)
    return text


_ELEMENTS_TAKES = {
    ("xml-attributes",): (
        "One function per declared object. Each takes the attributes of one element by\n"
        "the server's own names and hands them back in the order given, having refused\n"
        "a name the model does not declare and the absence of one a real element always\n"
        "carries. A double that builds every answer through these cannot invent a name.\n"
    ),
    ("json",): (
        "One function per declared object. Each takes the keys of one object by the\n"
        "server's own names and hands them back in the order given, having refused a\n"
        "name the model does not declare and the absence of one a real object always\n"
        "carries. A double that builds every answer through these cannot invent a name.\n"
    ),
    ("xml-attributes", "json"): (
        "One function per declared object. Each takes the attributes of one element, or\n"
        "the keys of one object, by the server's own names and hands them back in the\n"
        "order given, having refused a name the model does not declare and the absence\n"
        "of one a real answer always carries. A double that builds every answer through\n"
        "these cannot invent a name.\n"
    ),
}


class Elements:
    name = "metagen-elements"

    def generate(self, ctx):
        objects = model.read(ctx.loaded_root).objects
        used = {entry.format for entry in objects}
        formats = tuple(form for form in model.FORMATS if form in used) or (model.FORMATS[0],)
        content = (
            _header("elements")
            + '"""Builders for the answers a test double gives in place of the real server.\n'
            "\n" + _ELEMENTS_TAKES[formats] + '"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            + _assign("ELEMENT", {entry.key: entry.element for entry in objects})
            + "\n"
            + _assign("ATTRIBUTES", {entry.key: entry.fields for entry in objects})
            + "\n"
            + _assign("REQUIRED", {entry.key: entry.required for entry in objects})
            + "".join(_builder(form) for form in formats)
        )
        for entry in objects:
            words = _WORDS[entry.format]
            helper, members, whole = words["helper"], words["members"], words["whole"]
            content += (
                f"\n\ndef {entry.key}(**{members}) -> dict:\n"
                f'    """The {members} of one {entry.element} {whole}, as {entry.fqn} declares them."""\n'
                f'    return {helper}("{entry.key}", {members})\n'
            )
        return [EmittedFile(path="elements.py", content=content)]


_CONTRACT_HEAD = '''

def _capture() -> Path:
    """The capture, found from here: this file may be generated into any directory."""
    for parent in Path(__file__).resolve().parents:
        if (parent / CAPTURE_FILE).is_file():
            return parent / CAPTURE_FILE
    raise FileNotFoundError(f"no {CAPTURE_FILE} above {__file__}")


#: Why an attribute could not be observed, by the object's short name.
UNOBSERVED = {
    entry["key"]: entry["unobserved"] for entry in DECLARED.values() if entry["unobserved"]
}

'''

_CONTRACT_FAILS = '''

def never_sent(elements: dict, declared: dict = DECLARED) -> dict:
    """Declared attributes that no captured answer carries and no reason excuses."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        missing = sorted(set(entry["fields"]) - seen - set(entry["unobserved"]))
        if missing:
            found[fqn] = missing
    return found


def never_read(elements: dict, rows: dict = ROWS, declared: dict = DECLARED) -> dict:
    """Attributes a row reads that an answer it is built from never carries."""
    found = {}
    for key, row in rows.items():
        excused = set(declared[row["of"]]["unobserved"])
        for name in row["capture"]:
            missing = sorted(set(row["reads"]) - set(elements.get(name, ())) - excused)
            if missing:
                found[f"{key} row, from {name}"] = missing
'''

#: For a model in which some row reads another object: what it reads of that object
#: has to be in each of that object's own answers, by the same rule and the same excuse.
_NEVER_READ_ALSO = """        for fqn, reads in row["also"].items():
            excused = set(declared[fqn]["unobserved"])
            for name in declared[fqn]["capture"]:
                missing = sorted(set(reads) - set(elements.get(name, ())) - excused)
                if missing:
                    found[f"{key} row, {fqn} from {name}"] = missing
"""

_CONTRACT_TAIL = '''    return found


def undeclared(elements: dict, declared: dict = DECLARED) -> dict:
    """What the server sends and the model does not declare. Reported, never a failure."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        found[fqn] = sorted(seen - set(entry["fields"]))
    return found


def outlived(elements: dict, declared: dict = DECLARED) -> dict:
    """Reasons kept for an attribute a captured answer does carry. Reported only."""
    found = {}
    for fqn, entry in declared.items():
        seen = set().union(*(elements.get(name, ()) for name in entry["capture"]))
        stale = sorted(set(entry["unobserved"]) & seen)
        if stale:
            found[fqn] = stale
    return found


def report(elements: dict) -> str:
    """Both directions, in words: the one that fails and the one that only informs."""
    lines = []
    for fqn, extra in undeclared(elements).items():
        entry = DECLARED[fqn]
        lines.append(
            f"{fqn}: declares {len(entry['fields'])} attributes, "
            f"{len(entry['unobserved'])} of them with a reason they were not observed; "
            f"the captured server sends {len(extra)} more, which are not declared"
        )
        if extra:
            lines.append("  not declared: " + ", ".join(extra))
    for fqn, stale in outlived(elements).items():
        lines.append(f"{fqn}: a reason is kept for {stale}, which the capture now carries")
    failures = {**never_sent(elements), **never_read(elements)}
    for where, missing in failures.items():
        lines.append(f"FAIL {where}: {missing} is in no captured answer and has no reason")
    lines.append("capture check: " + ("FAILED" if failures else "passed"))
    return "\\n".join(lines) + "\\n"


if __name__ == "__main__":
    captured = answers()
    sys.stdout.write(report(captured))
    sys.exit(1 if never_sent(captured) or never_read(captured) else 0)
'''

_CONTRACT_TEST = """
from __future__ import annotations

import pytest

from . import capture_contract as contract

ELEMENTS = contract.answers()


@pytest.mark.parametrize("fqn", sorted(contract.DECLARED))
def test_every_declared_attribute_is_one_a_real_server_sent(fqn):
    missing = contract.never_sent(ELEMENTS, {fqn: contract.DECLARED[fqn]})
    assert missing == {}, (
        f"{missing} is declared and no captured answer carries it: it was invented, or it "
        "needs an `unobserved` reason saying why the capture could not have seen it"
    )


@pytest.mark.parametrize("key", sorted(contract.ROWS))
def test_every_attribute_a_row_reads_is_in_each_answer_it_is_built_from(key):
    missing = contract.never_read(ELEMENTS, {key: contract.ROWS[key]})
    assert missing == {}, f"{missing}: the column is empty everywhere but in the tests"
"""


def _answers(capture) -> str:
    """``answers()``, reading the section the model names and dropping what is not a name."""
    section = _string(capture.section)
    read = f'json.loads(Path(path or _capture()).read_text(encoding="utf-8"))[{section}]'
    head = (
        "\ndef answers(path=None) -> dict:\n"
        '    """The captured answers: the attribute names each one carried."""\n'
    )
    if not capture.list_suffix:
        return head + f"    return {read}\n"
    suffix = _string(capture.list_suffix)
    return head + (
        f"    captured = {read}\n"
        f"    # A name ending {suffix} records what a list held, beside the name of the list\n"
        "    # itself. It is not a name the server sent, so no check is shown it.\n"
        "    found = {}\n"
        "    for answer, names in captured.items():\n"
        f"        found[answer] = [name for name in names if not name.endswith({suffix})]\n"
        "    return found\n"
    )


def _reads_of(row) -> dict:
    """What a row needs each answer it is built from to carry, by object.

    Its own object, which appears always, carries every name a column reads and any
    map member keyed there; another object appears only when a column names it, and
    carries just the names read of it and the member keyed there.
    """
    owners: dict = {row.of: {name for names in row.reads.values() for name in names}}
    for others in row.also.values():
        for owner, names in others.items():
            owners.setdefault(owner, set()).update(names)
    for owner, member in row.key_of.values():
        owners.setdefault(owner, set()).add(member)
    return {owner: tuple(sorted(names)) for owner, names in owners.items()}


class CaptureContract:
    name = "metagen-capture-contract"

    def generate(self, ctx):
        loaded = model.read(ctx.loaded_root)
        objects, rows = loaded.objects, loaded.rows
        # Only this generator needs a capture, so only here is a model without one refused.
        capture = loaded.capture or model.capture(ctx.loaded_root)
        declared = {
            entry.fqn: {
                "key": entry.key,
                "capture": entry.capture,
                "fields": entry.fields,
                "unobserved": entry.unobserved,
            }
            for entry in objects
        }
        held = {row.key: _reads_of(row) for row in rows}
        reads = {
            row.key: {
                "of": row.of,
                "capture": row.capture,
                "reads": held[row.key][row.of],
            }
            for row in rows
        }
        others = {row.key: sorted(set(held[row.key]) - {row.of}) for row in rows}
        another = any(others.values())
        rows_are = (
            "#: Each row: the object it is read from, the answers it is built from, and the\n"
            "#: attributes it reads.\n"
        )
        if another:
            # Every row then says so, with nothing where it reads no other object: the
            # check that reads this is emitted once and asks each row the same thing.
            for row in rows:
                reads[row.key]["also"] = {owner: held[row.key][owner] for owner in others[row.key]}
            rows_are = (
                "#: Each row: the object it is read from, the answers it is built from, the\n"
                "#: attributes it reads of that object, and those it reads of any other.\n"
            )
        contract = (
            _header("capture_contract")
            + '"""What the model declares, held to a committed capture of a real server.\n'
            "\n"
            "It fails in one direction: an attribute that is declared, is in no captured\n"
            "answer, and carries no reason it could not be observed. That is an invented\n"
            "name, and whatever reads it is empty on every real server. The other direction\n"
            "is reported and never failed: a server sends far more than a tool reads, and\n"
            "the model declares what is read.\n"
            "\n"
            "Run this file to print both directions. The standard library is all it needs.\n"
            '"""\n'
            "\n"
            "from __future__ import annotations\n"
            "\n"
            "import json\n"
            "import sys\n"
            "from pathlib import Path\n"
            "\n"
            "#: The committed capture, as a path from the project root.\n"
            f"CAPTURE_FILE = {_string(capture.file)}\n"
            "\n"
            "#: Each declared object: the captured answers that show it, its attributes, and\n"
            "#: the reason for any that no capture could have seen.\n"
            + _assign("DECLARED", declared)
            + "\n"
            + rows_are
            + _assign("ROWS", reads)
            + _CONTRACT_HEAD
            + _answers(capture)
            + _CONTRACT_FAILS
            + (_NEVER_READ_ALSO if another else "")
            + _CONTRACT_TAIL
        )
        test = (
            _header("capture_contract")
            + '"""The capture check, as tests: see ``capture_contract`` beside this file."""\n'
            + _CONTRACT_TEST
        )
        return [
            EmittedFile(path="capture_contract.py", content=contract),
            EmittedFile(path="test_capture_contract.py", content=test),
        ]


rows, elements, capture_contract = Rows(), Elements(), CaptureContract()
